apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: expressjs-template-tk20230920
  title: Express.js Template by TK
  description: Creates a an Expressjs app for the StageCentral Workshop manually

spec:
  owner: user:guest
  type: app
  parameters:
                
steps:

output:
